"""Pydantic schemas for AI-powered laptop enrichment.

Defines the expected structure of the information generated by the AI.
This is the single source of truth for the output data contract — every
provider must return something that validates against this schema.
"""

from pydantic import BaseModel


class EnrichedListing(BaseModel):
    """Structured enrichment data generated from a laptop listing."""

    brand: str
    ram_gb: int | None
    storage_gb: int | None
    cpu: str | None
    category: str
    value_rating: str
    reasoning: str